// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcpumvlgbuttbetehqds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjcHVtdmxnYnV0dGJldGVocWRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1ODcxMDgsImV4cCI6MjA2NzE2MzEwOH0._ZtjtY2aZU_n6Q3C1pN-sKBnKZrtR72nLLjaIFPmDms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});